---
title: "Bike usage in Seattle 2014 - 2030"
author: "Chris Shaw"
date: "12 April 2019"
output: html_document
abstract: "<h5 style='font-style:italic'>This paper explores whether Seattle will reach its goal of quadrupling bike usage by 2030, as expressed in their [Bicycle Master Plan](http://www.seattle.gov/transportation/sdot-document-library/citywide-plans/modal-plans/bicycle-master-plan).  The data collected from city bike counters forms the basis of the projection model.
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=FALSE)
```


```{r include=FALSE}
library(tidyverse)
library(lubridate)
library(scales)
library(prophet)
library(purrr)

# set up a theme that can be added to plots

bg <- 'seashell'
datasource <- 'Source: Seattle Department of Transportation'

cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
theme <- list(
     theme_light() +
     theme(panel.grid.major = element_blank(),
           panel.grid.minor = element_blank(),
           panel.background = element_rect(fill = bg, colour = bg),
           axis.ticks = element_blank()
     ), 
     labs(caption=datasource),
     scale_color_manual(values=cbbPalette),
     scale_fill_manual(values=cbbPalette)
)

```


```{r echo=TRUE, message=FALSE, warning=FALSE}
# read in the data from disk - can uncomment the line below to retrieve from github if required
contest <- readr::read_csv2("https://raw.githubusercontent.com/RUsersAsturias/contest/gh-pages/_data/data%20w%20hour.csv")

```


```{r}
# look at speeding offences only
clean <- contest %>%
  filter(TYPE=='Velocidad') %>%
  mutate(PLACE=fct_lump(PLACE, 50),
         INFRACTION=fct_lump(INFRACTION, 20),
         date=ymd_hms(paste0(YEAR,'-',MONTH,'-',DAY, ' ', as.character(HOUR)))
         )

```


```{r}
clean %>% group_by(INFRACTION, PLACE) %>%
  tally() %>%
  spread(INFRACTION, n) %>%
  view()
```



```{r fig.height=15, fig.width=30}

clean %>%
  ggplot(aes(x=INFRACTION)) +
  geom_bar() +
  coord_flip()


clean %>%
  ggplot(aes(x=hour(date),y=stat(count))) +
  facet_wrap(.~weekdays(date)) +
  geom_bar(stat = "summary", fun.y = "mean") 
```
